### ISSUE TITLE
Spelling Error in introduction

### ISSUE THREAD

**Issue by InfoSec812** [redhat-appdev-practice/redhat-appdev-practice.github.io#52]
https://github.com/redhat-appdev-practice/website/blob/6c7cee1c2adb41a64bd02eeb47bd88cde268848d/src/tracks/bdd/README.md?plain=1#L18

**Comment by shayan-azizi** [comment]
Hi! i will fix that :)

**Comment by InfoSec812** [comment]
Awesome! I'll look forward to your pull request! Thank you for your contribution!

**Comment by ajukadavid** [comment]
hello, can i be assigned this issue?

**Comment by InfoSec812** [comment]
We don't assign issues on this project. If you would like to fix the error, please submit a pull request.

**Comment by ajukadavid** [comment]
Ok, will do.

**Comment by Ayushrawat-cmd** [comment]
is this still open?
