### ISSUE TITLE
Images not working on Staging Environment

### ISSUE THREAD

**Issue by jland-redhat** [redhat-appdev-practice/redhat-appdev-practice.github.io#68]
The way in which we do image URLs is using the absolute path, but the staging environment pre-pends `/website/` to the path which breaks all images.

Optimally if there is a builtin way with VUE to handle this that would be preferred but I was not able to find a simple solution. Another possibility is creating a regex that modifies the Markdown before building (but that could have strange unintended consequences to other items in the staging)

Not sure what the best solution is but it would be nice if the images were viewable.

**Comment by InfoSec812** [comment]
This is resolved by #76
